### DISCUSSION TITLE
How to define user details in pool with auth query enabled?

### DISCUSSION THREAD

**Discussion by AmythD** [postgresml/pgcat#918] [Q&A]
I have a question on how to define user credentials for pools when we have auth_query enabled -  
Is there a way to exclude user details inside pool details if we use auth_query?
The issue is that we have hundreds of databases and users and it would be difficult to list all user details within the pgcat config and then keep that list updated.

```
      auth_query_user: "admn_usr"
      auth_query_password: "admn_password"
      auth_query: "SELECT usename, passwd FROM pg_shadow WHERE usename='$1'"   
    pools:
      - name: "database1"      
        users:
          - username: "usr1"
            password: "usr1_password"                 
            pool_size: 4           
            statement_timeout: 0            
        shards:
          - servers:   
            - host: postgres.server.local              
              port: 5432
              role: primary
            database: database1
```
