### ISSUE TITLE
primary_reads_enabled doesn't behave as expected when pool_mode = "session"

### ISSUE THREAD

**Issue by osawyerr** [postgresml/pgcat#469]
**Describe the bug**
When ``primary_reads_enabled = false`` and  ``pool_mode = "session"``. If a psql client connects to the primary node (via pgcat) on first connection, it ignores ``primary_reads_enabled = false``. i.e. select queries are always sent from the primary node and never the replica.

**To Reproduce**
```toml
[pools.simple_db]
pool_mode = "session"
default_role = "replica"
query_parser_enabled = true
primary_reads_enabled = false
sharding_function = "pg_bigint_hash"

[pools.simple_db.shards.0]
servers = [
    [ "127.0.0.1", 5432, "primary" ],
    [ "localhost", 5431, "replica" ]
]
```

**Expected behavior**
One would expect that the inserts go to the primary while the selects go to the replicas.
