### ISSUE TITLE
tag container with release tags

### ISSUE THREAD

**Issue by DeoLeung** [postgresml/pgcat#484]
Hi,

It will be better if the container could be tagged using the release tags, 
it will be much more easy to find target versions.

**Comment by sebastianwebber** [comment]
@levkk what do you think about pushing the builds only in the main tag and all tags?

https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#example-including-branches-and-tags

the config in `build-and-push.yaml` will be something like this:

```yaml
# ...
on:
  push:
    branches:    
      - main
    tags:
      - v*
```

Let me know if you agree so I can send another PR.
