### ISSUE TITLE
The plpgsql funtion write data to some table need force route to primary database

### ISSUE THREAD

**Issue by mingjunyang** [postgresml/pgcat#485]
**Is your feature request related to a problem? Please describe.**
My plpgsql function need insert data to table, but I think current pgcat did not know my plpgsql function need only route to primary database.
```sql
CREATE TABLE write_test_table (
    ID bigserial PRIMARY KEY NOT NULL,
    info1 int,
    info2 int
);

CREATE OR REPLACE FUNCTION test_write_test_table ()
    RETURNS void
    AS $$
DECLARE
    t_count int;
BEGIN
    t_count := 0;
    LOOP
        RAISE NOTICE '%', t_count;
        t_count := t_count + 1;
        INSERT INTO write_test_table (info1, info2)
            VALUES (t_count, t_count * t_count);
        EXIT
        WHEN t_count = 10000;
    END LOOP;
END;
$$
LANGUAGE plpgsql;

```
my pgcat.toml
```toml
[general]
host = "0.0.0.0"
port = 6432

# Number of worker threads the Runtime will use (4 by default).
worker_threads = 8
prepared_statements = true
prepared_statements_cache_size = 500

admin_username = "postgres"
admin_password = "postgres"

[plugins]

[plugins.query_logger]
enabled = true

[pools.demo_db]
pool_mode = "transaction"
default_role = "primary"
query_parser_enabled = true
primary_reads_enabled = true
sharding_function = "pg_bigint_hash"

shards.0 = { servers = [["10.1.1.1", 5432, "primary"],["10.1.1.2", 5432, "replica"]], database = "demo_db"}
users.0 = { username = "postgres", password = "postgres", pool_size = 50 }
 
```

**Describe the solution you'd like**
Should we create a plugin , detect the query and force some appointed query route to primary database.
like those
```toml
[plugins.force_to_primary]
enabled = true
querys = [
  "select test_write_test_table()",
  "select test_write_test_table_xxx($1,$2)",
  regex".*\s+test_write_test_table\s+.*",
]
``` 

Or, have any implement the same function?
Or, I can set some config to got this function?
