### ISSUE TITLE
PgCat has higher overall latency / seems to swap connections around on k8s

### ISSUE THREAD

**Issue by timetinytim** [postgresml/pgcat#882]
**Describe the bug**
We attempted to replace pgbouncer with PgCat as our connection pooler for our kubernetes app, and encountered unexpected behavior. The average latency to the database seems to have increased ~15ms upon switching the web application over, and throughout our trial run, the 6 PgCat pods we created seemed to dramatically re-arrange their client connections whenever new pods were created or removed due to autoscalers, leading to even higher latency.

**To Reproduce**
1. Deploy the [helm chart](https://github.com/postgresml/pgcat/tree/main/charts/pgcat) with 6 replicas. (full config is below).
2. Point some 50~ high-traffic pods to the PgCat service.

**Expected behavior**
TPS and latency are expected to be, at least, on par with pgbouncer, ideally better. Additionally, client connections among each individual PgCat pod were expected to remain mostly stable, only increasing/decreasing as new pods and connections were created or removed, rather than the quite dramatic re-arrangements observed.

**Screenshots**
We enabled prometheus metrics for this trial, and graphed several metrics in datadog. Attached below are graphs showing `puma`'s response time for various components both before and after switching it to PgCat at around 11:40. The immediate increase in average latency is quite clear. After 12:00, as additional pods began spinning up (due to autoscalers), connections began jumping between the 6 PgCat pods at a surprising degree, further increasing the latency.

`puma`'s response time for its various services. The top light-blue segment represents latency to the DB.
![Screenshot from 2024-12-06 09-09-57](https://github.com/user-attachments/assets/d89b6731-a0bd-4938-8c7f-3936e28ba8d1)

PgCat client connections graphed per pod, per database. Each line is `cl_active` + `cl_idle` metrics to indicate total connections.
![Screenshot from 2024-12-06 09-10-16](https://github.com/user-attachments/assets/1c66f179-6591-4e16-9dd8-77718537199c)

PgCat server connection utilization percentage per pod, per database. Each line is `databases_current_connections` / `databases_pool_size` * 100) to give a percentage.
![Screenshot from 2024-12-06 09-10-28](https://github.com/user-attachments/assets/255464ea-c4ac-4849-8938-5cb4a18f5949)

**Kubernetes info:**
 - Version: 1.30 
 - Worker node OS: Ubuntu 22.04
 - PgCat version: v1.2.0

**Additional context**
Full config used for this trial:
```toml
[general]
host = "0.0.0.0"
port = 6432
enable_prometheus_exporter = true
prometheus_exporter_port = 9930
connect_timeout = 15000
idle_timeout = 600000
server_lifetime = 3600000
server_tls = false
idle_client_in_transaction_timeout = 0
healthcheck_timeout = 1000
healthcheck_delay = 30000
shutdown_timeout = 60000
ban_time = 60
log_client_connections = false
log_client_disconnections = false
tcp_keepalives_idle = 5
tcp_keepalives_count = 5
tcp_keepalives_interval = 5
admin_username = XXXXXXXX
admin_password = XXXXXXXX

##
## pool for primary
##
[pools."primary"]
pool_mode = "transaction"
load_balancing_mode = "random"
default_role = "any"
prepared_statements_cache_size = 500
query_parser_enabled = false
primary_reads_enabled = true
sharding_function = "pg_bigint_hash"

##
## pool for replica
##
[pools."replica"]
pool_mode = "transaction"
load_balancing_mode = "random"
default_role = "any"
prepared_statements_cache_size = 500
query_parser_enabled = false
primary_reads_enabled = true
sharding_function = "pg_bigint_hash"

## pool primary user
##
[pools."primary".users.0]
username = XXXXXXXX
password = XXXXXXXX
pool_size = 200
statement_timeout = 0
min_pool_size = 3

## pool replica user
##
[pools."replica".users.0]
username = XXXXXXXX
password = XXXXXXXX
pool_size = 200
statement_timeout = 0
min_pool_size = 3

## pool primary database mastodon
##
[pools."primary".shards.0]
servers = [
    [ "10.1.1.6", 5432, "primary" ],
]
database = "webapp"

## pool replica database mastodon
##
[pools."replica".shards.0]
servers = [
    [ "10.1.1.7", 5432, "primary" ],
]
database = "webapp"
```

This issue is potentially related to another high-latency issue https://github.com/postgresml/pgcat/issues/459. Also tagging https://github.com/postgresml/pgcat/issues/872 as they are having performance issues with their attempt.
