### ISSUE TITLE
Docker won't run on Raspberry Pi 5 - <jemalloc>: Unsupported system page size

### ISSUE THREAD

**Issue by Snuffy2** [postgresml/pgcat#922]
**Describe the bug**
When trying to run pgcat in Docker on a Raspberry Pi 5, I get the error below and the container won't start. I've tried on 2 different RPi5 with the same error. If I run the container on a Raspberry Pi 4, it works. All 3 RPi are running Debian Bookworm and Docker 28.0.4. 

It may not be differences in the RPi5 vs 4 but I'm not sure what else to look into. Any ideas to further trouble shoot would be much appreciated.

**docker-compose.yml**
docker-compose.yml
```yml
  pgcat:
    image: ghcr.io/postgresml/pgcat:latest
    networks:
      - snuffy2-network
    ports:
      - 5432:5432 # postgres
      # - 9930:9930 # prometheus
    environment:
      TZ: America/New_York
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /mnt/gfs/swarm/appdata/pgcat/config/pgcat.toml:/etc/pgcat/pgcat.toml
```

**Docker Logs**
```
<jemalloc>: Unsupported system page size
<jemalloc>: Unsupported system page size
memory allocation of 56 bytes failed
```
