### ISSUE TITLE
Empty password with auth proxy does not work

### ISSUE THREAD

**Issue by sandangel** [postgresml/pgcat#926]
**Describe the bug**

We use auth proxy with auto IAM auth so we will have to submit empty password, but pgcat does not allow

**To Reproduce**
1. Create alloydb instance with alloydb auth proxy
2. deploy alloydb auth proxy with auto  iam
3. deploy pgcat with user and empty password
4. pgcat does not work

**Expected behavior**
pgcat should support empty password

**Additional context**

pgcat version v1.2.0

```toml
# https://github.com/postgresml/pgcat/blob/main/pgcat.toml
[general]
host = "0.0.0.0"
port = 6432
enable_prometheus_exporter = true
prometheus_exporter_port = 9930
admin_username = "admin"
admin_password = "admin"
admin_auth_type = "trust"
worker_threads = 10
connect_timeout = 5000
idle_timeout = 30000
autoreload = 15000

[plugins]
[plugins.prewarmer]
enabled = false
queries = [
  "SELECT pg_prewarm('pgbench_accounts')",
]

[pools.foo]
pool_mode = "session"
query_parser_enabled = true
query_parser_read_write_splitting = true
load_balancing_mode = "loc"

[pools.foo.users.1]
username = "svc-test@gcp-project.iam"
password = ""
auth_type = "trust"
pool_size = 100
min_pool_size = 3

[pools.foo.shards.0]
servers = [["localhost", 5432, "primary"], ["localhost", 5433, "replica"]]
database = "foo"

[pools.bar]
pool_mode = "session"
query_parser_enabled = true
query_parser_read_write_splitting = true
load_balancing_mode = "loc"

[pools.bar.users.1]
username = "svc-test@gcp-project.iam"
password = ""
auth_type = "trust"
pool_size = 100
min_pool_size = 3


[pools.bar.shards.0]
servers = [["localhost", 5432, "primary"], ["localhost", 5433, "replica"]]
database = "bar"

```
